### ISSUE TITLE
Question about the results

### ISSUE THREAD

**Issue by sgmath12** [Muzammal-Naseer/NRP#1]
- In the Table 2, What is **Comics** and **Paintings**? 

- The ImageNet result on the Table 2, is it Top-1 accuracy or Top-5 accuracy? If it is the Top-1 accuracy, then it doesn't make sense since the accuracy of SOTA of ImageNet still under 90%.

- Same question with above, in figure 5, you wrote the Top-1 accuracy for IncRes-V2 on Imagenet, and the result is higher than 90% on clean image.

-  In the Table 2,  what does the number mean on Detection and Segmention results?

**Comment by Muzammal-Naseer** [comment]
Hi,

Comics and Paintings are the datasets used in this paper "[Cross-Domain Transferability of Adversarial Perturbations](https://arxiv.org/abs/1905.11736)" to train generators for adversarial transerability. Details are available in above-mentioned paper.


In Table2 Top-1 accuracy is reported on ImageNet-NeurIPS datasets. It contains 1000 images and used in different competitions and papers such as  [Cross-Domain Transferability of Adversarial Perturbations](https://arxiv.org/abs/1905.11736). 

In figure 5, Top-1 accuracy is reported on the ImageNet-NeurIPS dataset.

In Table 2, what does the number mean on Detection and Segmentation results? Can you please rephrase this question?  For example, detection results indicate mAP-50 in Table2.

**Comment by sgmath12** [comment]
Thanks for your quick response,

I think word like _NIPS 2017 challenge dataset (1k samples)_  is more appropriate than  _ImageNet-NeurIPS_ dataset since it is not kind of official words. 

For other questions, just ignore.

Thanks
