### ISSUE TITLE
Question about "success rate"

### ISSUE THREAD

**Issue by dsanno** [Muzammal-Naseer/NRP#5]
Hi, thanks for your sharing first.
I'd like to know metrics in your paper to compare adversarial attack/defense methods.

What is "success rate" in Table 1 ?
Could you please tell me the equation or code to calculate success rate ?

**Comment by Muzammal-Naseer** [comment]
Hi,

Please note that "The success rates are the misclassification rates of the corresponding models with adversarial
images as input"

Thanks

**Comment by dsanno** [comment]
Thank you. I got it.
