### ISSUE TITLE
critic networks

### ISSUE THREAD

**Issue by yearep7** [Muzammal-Naseer/NRP#7]
Can you tell me which py file it is  the structure of critic networks

**Comment by Muzammal-Naseer** [comment]
Hi,

NRP training is based on the following framework: https://github.com/xinntao/BasicSR.

Please have a look at the following file: https://github.com/XPixelGroup/BasicSR/blob/81af6f583a31ca870f120007d9a05667ef5b0056/basicsr/archs/discriminator_arch.py

Thanks
